[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
  command = "chmod 755 ./scripts/build.sh && chmod 755 ./scripts/test.js && chmod 755 ./scripts/ffmpeg-path.js && sh ./scripts/build.sh"
  functions = "lambda" #  netlify-lambda reads this
  publish = "build"